name: Build PowerShell Script to EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          iex "& { $(irm https://aka.ms/install-powershell.ps1) }"
          pwsh -command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy RemoteSigned"

      - name: Install PS2EXE
        run: |
          Install-Module -Name ps2exe -RequiredVersion 1.0.4

      - name: Convert PowerShell Script to EXE
          
        run: |
          ps2exe .\osquery_script.ps1 -output .\osquery_script.exe -runtime64 -noconsole
          
        

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v2
        with:
          name: osquery_script_exe
          path: osquery_script.exe
