name: Convert PowerShell to EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up PowerShell
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        iex "& { $(irm https://aka.ms/install-powershell.ps1) }"
        pwsh -command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy RemoteSigned"

    - name: Install PS2EXE module
      shell: powershell
      run: |
        Install-Module ps2exe -Force
    - name: Convert PowerShell script to EXE file
      shell: powershell
      run: |
        Invoke-ps2exe -input "osquery_script.ps1" -output "osquery_script.exe"
    - name: Upload EXE file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: script.exe
        path: ./osquery_script.exe



