name: Convert PowerShell to EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PS2EXE module
      shell: powershell
      run: |
        Install-Module ps2exe -Force
    - name: Convert PowerShell script to EXE file
      shell: powershell
      run: |
        Invoke-ps2exe -inputFile .\osquery_script.ps1 -outputFile .\osquer_script.exe
    - name: Upload EXE file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: script.exe
        path: .\osquery_script.exe




